[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-pptx>=1.0.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "boto3>=1.40.16",
    "dotenv>=0.9.9",
]
